name: Run Pull Request CI Tests
on:
  pull_request:
    branches:
      - 'gh-pages'
jobs:
  Run-Pull-Request-CI-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set permissions for Jekyll
        run: chmod -R 777 .

      - name: Run E2E tests
        env:
            NO_LIVERELOAD: true
        run: docker compose --profile e2e up --exit-code-from hfla_e2e --abort-on-container-exit